server:
  port: 80
  ssl:
      key-store-type: JKS
      key-store: classpath:mykey.jks
      key-store-password: Hl7!JP4J*7Ka@kLN
      key-alias: server
app:
  app_id: tt654b13f6fa7d5b6910
  app_secret: d60130eecb7ba6803bd56f984ae822ceed5e1d73 
  app_grant_type: client_credential
  app_room_id: 1120981200010014472
  app_sec_gift_id_list: n1/Dg1905sj1FyoBlQBvmbaDZFBNaKuKZH6zxHkv8Lg5x2cRfrKUTb8gzMs=,
    28rYzVFNyXEXFC8HI+f/WG+I7a6lfl3OyZZjUS+CVuwCgYZrPrUdytGHu0c=,
    PJ0FFeaDzXUreuUBZH6Hs+b56Jh0tQjrq0bIrrlZmv13GSAL9Q1hf59fjGk=,
    IkkadLfz7O/a5UR45p/OOCCG6ewAWVbsuzR/Z+v1v76CBU+mTG/wPjqdpfg=,
    gx7pmjQfhBaDOG2XkWI2peZ66YFWkCWRjZXpTqb23O/epru+sxWyTV/3Ufs=,
    P7zDZzpeO215SpUptB+aURb1+zC14UC9MY1+MHszKoF0p5gzYk8CNEbey60=
  private_key_pem:
                  path: classpath:private_key.pem
    
