server:
  port: 8000
 # ssl:
 #   key-store-type: JKS
 #   key-store: classpath:mykey.jks
 #   key-store-password: Hl7!JP4J*7Ka@kLN
 #   key-alias: server 
app:
  app_id: tt654b13f6fa7d5b6910
  app_secret: d60130eecb7ba6803bd56f984ae822ceed5e1d73 
  app_grant_type: client_credential
